FROM tianon/true

COPY components/statestore.yaml /components/statestore.yaml
COPY components/pubsub.yaml /components/pubsub.yaml
COPY components/video-recorded-subscription.yaml /components/video-recorded-subscription.yaml

COPY config/config.yaml /config/config.yaml

VOLUME /components
VOLUME /config