services:
  video-recorder1:
    container_name: video-recorder1
    environment:
      - EMAIL=${EMAIL}
      - PASSWORD=${PASSWORD}
      - VIDEO_TO_RECORD_ID=0
    extends:
      service: video-recorder
      file: common-services.yaml
  video-recorder2:
    container_name: video-recorder2
    environment:
      - EMAIL=${EMAIL}
      - PASSWORD=${PASSWORD}
      - VIDEO_TO_RECORD_ID=2
    extends:
      service: video-recorder
      file: common-services.yaml
  video-recorder3:
    container_name: video-recorder3
    environment:
      - EMAIL=${EMAIL}
      - PASSWORD=${PASSWORD}
      - VIDEO_TO_RECORD_ID=4
    extends:
      service: video-recorder
      file: common-services.yaml
  video-recorder4:
    container_name: video-recorder4
    environment:
      - EMAIL=${EMAIL}
      - PASSWORD=${PASSWORD}
      - VIDEO_TO_RECORD_ID=6
    extends:
      service: video-recorder
      file: common-services.yaml
  video-recorder5:
    container_name: video-recorder5
    environment:
      - EMAIL=${EMAIL}
      - PASSWORD=${PASSWORD}
      - VIDEO_TO_RECORD_ID=8
    extends:
      service: video-recorder
      file: common-services.yaml
