services:
  video-server:
    container_name: video-server
    build:
      context: src/video-server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - config/.env.video-server
    restart: unless-stopped
    healthcheck:
      test: exit 0
      start_period: 10s
    develop:
      watch:
        - path: ./src/video-server/main.go
          action: rebuild

  video-server-dapr:
    container_name: video-server-dapr
    image: daprio/daprd:1.13.5
    command:
      [
        "./daprd",
        "-app-id",
        "video-server",
        "-app-port",
        "3000",
        "-placement-host-address",
        "dapr-placement:40000",
        "-dapr-http-port",
        "3500",
        "-dapr-grpc-port",
        "50001",
        "-resources-path",
        "/components",
        "-config",
        "/config/config.yaml",
      ]
    volumes_from:
      - dapr-config
    restart: unless-stopped
    depends_on:
      video-server:
        condition: service_started
      dapr-placement:
        condition: service_started
      dapr-config:
        condition: service_started
    network_mode: "service:video-server"

  video-merger:
    container_name: video-merger
    build:
      context: src/video-merger
      dockerfile: Dockerfile
    ports:
      - "8080"
    env_file:
      - config/.env.video-merger
    restart: unless-stopped
    volumes:
      - ${VIDEO_DIR_PATH}:/temp/videos
    develop:
      watch:
        - path: ./src/video-merger/main.go
          action: rebuild

  video-merger-dapr:
    container_name: video-merger-dapr
    image: daprio/daprd:1.13.5
    command:
      [
        "./daprd",
        "-app-id",
        "video-merger",
        "-app-port",
        "8080",
        "-placement-host-address",
        "dapr-placement:40000",
        "-dapr-http-port",
        "3501",
        "-dapr-grpc-port",
        "50002",
        "-resources-path",
        "/components",
        "-config",
        "/config/config.yaml",
      ]
    volumes_from:
      - dapr-config
    restart: unless-stopped
    depends_on:
      video-merger:
        condition: service_started
      dapr-placement:
        condition: service_started
      dapr-config:
        condition: service_started
    network_mode: "service:video-merger"

  video-converter:
    container_name: video-converter
    build:
      context: src/video-converter
      dockerfile: Dockerfile
    ports:
      - "8081"
    env_file:
      - config/.env.video-converter
    restart: unless-stopped
    volumes:
      - ${VIDEO_DIR_PATH}:/temp/videos
    develop:
      watch:
        - path: ./src/video-converter/main.go
          action: rebuild

  video-converter-dapr:
    container_name: video-converter-dapr
    image: daprio/daprd:1.13.5
    command:
      [
        "./daprd",
        "-app-id",
        "video-converter",
        "-app-port",
        "8081",
        "-placement-host-address",
        "dapr-placement:40000",
        "-dapr-http-port",
        "3502",
        "-dapr-grpc-port",
        "50003",
        "-resources-path",
        "/components",
        "-config",
        "/config/config.yaml",
      ]
    volumes_from:
      - dapr-config
    restart: unless-stopped
    depends_on:
      video-converter:
        condition: service_started
      dapr-placement:
        condition: service_started
      dapr-config:
        condition: service_started
    network_mode: "service:video-converter"

  video-compressor:
    container_name: video-compressor
    build:
      context: src/video-compressor
      dockerfile: Dockerfile
    ports:
      - "8082"
    env_file:
      - config/.env.video-compressor
    restart: unless-stopped
    volumes:
      - ${VIDEO_DIR_PATH}:/temp/videos
    develop:
      watch:
        - path: ./src/video-compressor/main.go
          action: rebuild

  video-compressor-dapr:
    container_name: video-compressor-dapr
    image: daprio/daprd:1.13.5
    command:
      [
        "./daprd",
        "-app-id",
        "video-compressor",
        "-app-port",
        "8082",
        "-placement-host-address",
        "dapr-placement:40000",
        "-dapr-http-port",
        "3503",
        "-dapr-grpc-port",
        "50004",
        "-resources-path",
        "/components",
        "-config",
        "/config/config.yaml",
      ]
    volumes_from:
      - dapr-config
    restart: unless-stopped
    depends_on:
      video-compressor:
        condition: service_started
      dapr-placement:
        condition: service_started
      dapr-config:
        condition: service_started
    network_mode: "service:video-compressor"

  dapr-placement:
    container_name: dapr-placement
    image: daprio/placement:1.13.5
    command: ["./placement", "-port", "40000", "-log-level", "debug"]
    ports:
      - "40000"
    restart: unless-stopped
    depends_on:
      zipkin:
        condition: service_started
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379"
    restart: unless-stopped
    volumes:
      - redis-data:/data

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
      - "5672"
      - "15672:15672"
    restart: unless-stopped
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - rabbitmq-logs:/var/log/rabbitmq

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin:latest
    ports:
      - "19411:9411"
    restart: unless-stopped

  dapr-config:
    container_name: dapr-config
    build:
      context: ./dapr
      dockerfile: Dockerfile

volumes:
  redis-data:
    driver: local
  rabbitmq-data:
    driver: local
  rabbitmq-logs:
    driver: local

networks:
  default:
    name: course-crawler-network
    driver: bridge
