services:
  video-recorder1:
    container_name: video-recorder1
    environment:
      - EMAIL=${EMAIL}
      - PASSWORD=${PASSWORD}
      - VIDEO_TO_RECORD_ID=0
    extends:
      service: video-recorder
      file: common-services.yaml
  video-recorder2:
    container_name: video-recorder2
    environment:
      - EMAIL=${EMAIL}
      - PASSWORD=${PASSWORD}
      - VIDEO_TO_RECORD_ID=1
    extends:
      service: video-recorder
      file: common-services.yaml
