apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
    - name: connectionString
      value: "amqp://rabbitmq:5672"
    - name: durable
      value: "false"
    - name: deletedWhenUnused
      value: "false"
    - name: autoAck
      value: "false"
    - name: reconnectWait
      value: "0"
    - name: concurrency
      value: parallel
    - name: enableDeadLetter
      value: "true"
    - name: deliveryMode
      value: "2"
    - name: allowedTopics
      value: "video-recorded;video-merged;video-converted;"
    - name: publishingScopes
      value: "video-server=video-recorded;video-merger=video-merged;video-converter=video-converted;"
    - name: subscribingScopes
      value: "video-merger=video-recorded;video-converter=video-merged;video-compressor=video-converted;"
scopes:
  - video-server
  - video-merger
  - video-converter
  - video-compressor
