apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: video-merged-subscription
spec:
  topic: video-merged
  routes:
    default: /videos/convert
  pubsubname: pubsub
scopes:
  - video-converter
