apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: video-recorded-subscription
spec:
  topic: video-recorded
  routes:
    default: /videos/merge
  pubsubname: pubsub
scopes:
  - video-merger